### PR TITLE
update

### PR DESCRIPTION
**Pull request by neighborhood999**

### CODE REVIEW

**Comment by kevingo** [comment]
@neighborhood999 Thanks for updating.

**Comment by kevingo** [comment]
By the way, I will put your name on the contributor in README, please check : [https://github.com/kevingo/the-little-go-book/blob/master/README.md](https://github.com/kevingo/the-little-go-book/blob/master/README.md)

Is it ok for you ?

**Comment by neighborhood999** [comment]
@kevingo Thanks! But I thinking I don't have more contribution on translation, just fix typo and others xd.
Maybe you can add **Contributor** on README.

**Comment by kevingo** [comment]
@neighborhood999 Sure, I will add Contributor section. 👍

**Pull request merged**
