### PR TITLE
gitbook support

### PR DESCRIPTION
**Pull request by neighborhood999**
We can build this file and deploy on Github pages for convenient to reading.

### CODE REVIEW

**Comment by neighborhood999** [comment]
We can build this file and deploy on Github pages for convenient to reading.

**Comment by kevingo** [comment]
@neighborhood999 cool.

**Comment by neighborhood999** [comment]
@kevingo you can reference [here](https://github.com/neighborhood999/webpack-tutorial-gitbook/blob/master/deploy.sh), my previous experience for auto deploy.

**Comment by kevingo** [comment]
@neighborhood999 ok, thanks !

**Pull request merged**
